name: Minify

on: push

jobs:
  minify:
    env:
      NODEJS_VERSION: "23"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.NODEJS_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODEJS_VERSION }}
      - run: |
          npm ci
          npm run minify --if-present
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: 'dist/*.min.js'
